import type { Metadata } from "next";
import ClientLoadingLayout from "./appLayout"; 
import "./globals.css";

// Metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* Wrap children with ClientLoadingLayout */}
        <ClientLoadingLayout>
          {children}
        </ClientLoadingLayout>
      </body>
    </html>
  );
}
